sudo: false
language: python
python:
    - '2.7'
    - '3.4'
    - '3.5'
    - '3.6'
    - 'pypy3.5'
script:
    - py.test --strict -vv tests
install:
    - pip install .
    - pip install pytest-localserver
os:
    - linux
