sudo: false
language: python
python:
    - '2.6'
    - '2.7'
    - '3.2'
    - '3.3'
    - '3.4'
    - 'pypy'
    - 'pypy3'
script: make
install:
    - python setup.py install
    - python setup.py test
os:
    - linux
