sudo: false
language: python
python:
    - '2.7'
    - '3.2'
    - '3.3'
    - '3.4'
    - 'pypy'
    - 'pypy3'
script:
    - py.test --cov=harlequin --strict -vv tests
after_success:
    - pip install codeclimate-test-reporter
    - codeclimate-test-reporter
install:
    - pip install .
    - pip install pytest-localserver
    - pip install pytest-cov
os:
    - linux
