sudo: false
language: python
python:
    - '2.7'
    - '3.2'
    - '3.3'
    - '3.4'
    - 'pypy'
    - 'pypy3'
script: py.test --strict -vv tests
install:
    - pip install .
    - pip install pytest-localserver
os:
    - linux
