sudo: false
language: python
python:
    - '2.6'
    - '2.7'
    - '3.2'
    - '3.3'
    - '3.4'
    - 'pypy'
    - 'pypy3'
script: make
install:
    - pip install .
    - pip install pytest-cov pytest-localserver
os:
    - linux
