build: off
environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python37"

install:
  - "%PYTHON%\\python.exe -m pip install wheel"
  - "%PYTHON%\\python.exe -m pip install ."
  - "%PYTHON%\\python.exe -m pip install pytest pytest-localserver"

test_script:
  - "%PYTHON%\\python.exe -m pytest"
